host: http://localhost:8100/api/v1/links

server:
  port: "8100"

linker:
  short-url:
    length: 6
    max-attempts: 64
  expiration-days: 30

spring:
  data:
    mongodb:
      database: links
      uri: mongodb://localhost:27017/?directConnection=true/links
#      uri: mongodb+srv://inikki:PASSWORD@mymongoinaws.pdq9e7w.mongodb.net/links

springdoc:
  swagger-ui:
    # Tag groups (controllers) sorted A -> Z
    tagsSorter: alpha
    # Operations sorted A -> Z by path within each tag
    operationsSorter: alpha
