Feature: test PostRankingController

  # ═══════════════════════════════════════════════════════════════════════════════
  # FIXTURE DATA  (src/test/resources/data/csv/)
  # Generated by EventGenerator implementations in cucumber/helper/generator/.
  # Run EventGeneratorTest to regenerate fresh CSV files before Cucumber tests.
  # ═══════════════════════════════════════════════════════════════════════════════
  # Five CSV files, 50 posts total. Events per file differ:
  #   4 generators × 100 users × 10 posts =  4 000 events
  #   TopVotesGenerator × 500 users × 10 posts = 5 000 events   (500 needed — see below)
  #   ──────────────────────────────────────────────────────────
  #   Total                                    =  9 000 events
  #
  # Each file targets a specific time band so that every Top window and the Best sort
  # have a different winner — no two sorts share the same top-10 posts.
  # Files share no post IDs and can be ingested in parallel.
  #
  # Columns: userId, postId, action (UPVOTE|DOWNVOTE), date (ISO-8601 UTC)
  #
  # ┌──────────────────────┬───────────┬─────────────┬──────────┬──────────────────────────────────────────────┐
  # │ File                 │ Posts     │ voters/post │ upvote % │ Date pattern / intent                        │
  # ├──────────────────────┼───────────┼─────────────┼──────────┼──────────────────────────────────────────────┤
  # │ events-hot.csv       │ post-11…20│     100     │  62–71%  │ post.createdAt = 9–54 min ago                │
  # │                      │           │             │          │ → wins Hot + Top DAY + Top WEEK              │
  # ├──────────────────────┼───────────┼─────────────┼──────────┼──────────────────────────────────────────────┤
  # │ events-new.csv       │ post-21…30│     100     │  51–60%  │ post.createdAt = 1–10 s ago (explicit)       │
  # │                      │           │             │          │ → most recent createdAt → wins New feed      │
  # ├──────────────────────┼───────────┼─────────────┼──────────┼──────────────────────────────────────────────┤
  # │ events-rising.csv    │ post-31…40│     100     │  72–81%  │ All events 8–29 days ago                     │
  # │                      │           │             │          │ → inside MONTH, outside WEEK → Top MONTH     │
  # ├──────────────────────┼───────────┼─────────────┼──────────┼──────────────────────────────────────────────┤
  # │ events-best.csv      │ post-01…10│     100     │  83–92%  │ All events 31–364 days ago                   │
  # │                      │           │             │          │ → inside YEAR, outside MONTH → Top YEAR      │
  # │                      │           │             │          │ → wins Best ⭐ (Wilson 0.745–0.850)          │
  # ├──────────────────────┼───────────┼─────────────┼──────────┼──────────────────────────────────────────────┤
  # │ events-top.csv       │ post-41…50│     500     │  61–70%  │ All events 366–730 days ago                  │
  # │                      │           │             │          │ → outside YEAR; only Top ALL counts them     │
  # │                      │           │             │          │   500 voters × low ratio → karma 110-200,    │
  # │                      │           │             │          │   beats BestEvents karma ceiling (84)        │
  # │                      │           │             │          │ → Wilson 0.567–0.658, loses Best ⭐          │
  # └──────────────────────┴───────────┴─────────────┴──────────┴──────────────────────────────────────────────┘
  #
  # ── KARMA IS UNIQUE PER POST ─────────────────────────────────────────────────────────────────────
  #
  # isUpvote() uses a deterministic hash: bucket = floorMod(userId*31 + postId*17, 100); gcd(31,100)=1
  # → for userId 1-100 the buckets are a full permutation of 0-99
  # → upvotePercent% of the 100 users always upvote for any given postId
  # → for n=500 users (5 complete cycles of 1-100): exactly 5×upvotePercent upvote
  #
  # karma formula:
  #   n=100: karma = 2 × upvotePercent − 100
  #   n=500: karma = 500 × (2 × upvotePercent/100 − 1) = 10 × (2 × upvotePercent − 100)
  #
  #   posts 21-30  karma   2,   4, …   20  (NewEvents,    51–60%, n=100)  → New feed
  #   posts 11-20  karma  24,  26, …   42  (HotEvents,    62–71%, n=100)  → Hot + Top DAY + Top WEEK
  #   posts 31-40  karma  44,  46, …   62  (RisingEvents, 72–81%, n=100)  → Top MONTH
  #   posts 01-10  karma  66,  68, …   84  (BestEvents,   83–92%, n=100)  → Top YEAR + Best ⭐
  #   posts 41-50  karma 110, 120, …  200  (TopEvents,    61–70%, n=500)  → Top ALL
  #
  # ── EXPECTED RANKING DIFFERENCES ──────────────────────────────────────────────────────────────────
  #
  # Hot  (Reddit formula: hot_score = log₁₀(karma) + (post.createdAt − 1134028003) / 45 000)
  #   Time dominates — every 12.5 h of age costs ~1 hot_score point.
  #   posts 11-20: createdAt ≈  9–54 min, karma   24–  42  → wins Hot (9–54 min fresher than NewEvents,
  #                                                           karma advantage ensures margin > 0)
  #   posts 21-30: createdAt ≈ 1–10 s,   karma    2–  20  → 2nd (newer but lower karma)
  #   posts 31-40: createdAt ≈ 8–29 d,   karma   44–  62  → 3rd place
  #   posts  1-10: createdAt ≈ 364 d,    karma   66–  84  → 4th place
  #   posts 41-50: createdAt ≈ 730 d,    karma 110– 200   → last (time penalty too large)
  #
  # Top  (top_score = upvotes − downvotes, filtered by window)
  #
  #   Window │ Winner        │ Why
  #   ───────┼───────────────┼───────────────────────────────────────────────────────────────
  #   DAY    │ posts 11-20   │ createdAt 9-54 min ago; karma 24-42 > NewEvents karma 2-20
  #   WEEK   │ posts 11-20   │ createdAt 9-54 min ago; karma 24-42 > NewEvents karma 2-20;
  #          │               │ RisingEvents createdAt 8-29 d → outside 7-day window
  #   MONTH  │ posts 31-40   │ 8-29 d old → in MONTH, not in WEEK; karma 44-62 > 42
  #   YEAR   │ posts 01-10   │ 31-364 d old → in YEAR, not in MONTH; karma 66-84 > 62
  #   ALL    │ posts 41-50   │ 366-730 d old → only visible in ALL; karma 110-200 > 84
  #
  # Best ⭐ (Wilson score lower bound, 95 % confidence, no time filter)
  #
  #   posts 01-10 (83–92 %, n=100): Wilson 0.745–0.850 → WIN
  #   posts 41-50 (61–70 %, n=500): Wilson 0.567–0.658 → lose (lower ratio dominates despite more voters)
  #   Why not 91-100 % for TopVotesGenerator? Wilson is asymptotically bounded by the ratio:
  #   Wilson(70 %) → 0.70 as n→∞, so 70 % can NEVER beat 83 % regardless of sample size.
  #   Dropping TopVotesGenerator to 61-70 % is the only way to let posts 01-10 win Best.
  # ═══════════════════════════════════════════════════════════════════════════════════

  Scenario: prepare data
    Given index 'posts' is recreated
    Given index 'user-votes' is recreated
    Given data folder 'data/csv' created in tmp directory
    Given data folder 'data/csv' ingested

  # Best ranking: Wilson score lower bound (95% confidence interval on upvote ratio).
  # Rewards posts that are both reliably upvoted AND have enough votes to be statistically significant.
  #
  # BestEvents (posts 01-10): upvote% 83–92%, 100 voters each
  #   → Wilson scores ≈ 0.745 (post-01, 83%) to 0.850 (post-10, 92%) → WIN
  # TopEvents (posts 41-50): upvote% 61–70%, 500 voters each
  #   → Wilson scores ≈ 0.567 (post-41, 61%) to 0.658 (post-50, 70%) → lose
  #
  # Why TopEvents lose despite more voters: Wilson score is asymptotically bounded by the
  # upvote ratio — Wilson(70%) → 0.70 as n→∞, so 70% can never reach the BestEvents
  # minimum of 0.745 (83% upvote ratio). More voters narrow the interval but can't raise
  # the ceiling above the true proportion.
  #
  # Wilson score ordering within BestEvents is strictly by upvote%:
  #   post-10 (92%): 0.850 > post-09 (91%): 0.838 > ... > post-01 (83%): 0.745
  # karma per post: postId 01→66, 02→68, ..., 10→84  (upvote% = 83 + (postId−1))
  Scenario: Best posts
    Given data folder 'data/csv' was ingested
    Then best posts endpoint returns 10 ranked results
      | postId  | karma |
      | post-10 | 84    |
      | post-09 | 82    |
      | post-08 | 80    |
      | post-07 | 78    |
      | post-06 | 76    |
      | post-05 | 74    |
      | post-04 | 72    |
      | post-03 | 70    |
      | post-02 | 68    |
      | post-01 | 66    |

  # Hot ranking: Reddit's hot_score = log₁₀(karma) + (post.createdAt − anchor) / 45 000.
  # Time dominates, but karma advantage compensates the small gap vs. NewEvents (1–10 s old).
  # Worst-case margin: log₁₀(24/20) − 3239/45000 = +0.0072 > 0 → posts 11-20 always win Hot.
  # karma per post: postId 11→24, 12→26, ..., 20→42  (upvote% = 62 + (postId−11))
  Scenario: Hot posts
    Given data folder 'data/csv' was ingested
    Then hot posts endpoint returns 10 ranked results
      | postId  | karma |
      | post-20 | 42    |
      | post-19 | 40    |
      | post-18 | 38    |
      | post-17 | 36    |
      | post-16 | 34    |
      | post-15 | 32    |
      | post-14 | 30    |
      | post-13 | 28    |
      | post-12 | 26    |
      | post-11 | 24    |

  # New ranking: sorted by post.createdAt DESC from the 'posts' index (actual submission time).
  # NewEvents (posts 21-30): createdAt is within the last 10 minutes
  # (post-30 is newest, post-21 is oldest in this generator).
  # HotEvents (posts 11-20): createdAt = 9–54 minutes ago — older than NewEvents ordering for post-30..21.
  #
  # Why Hot posts still win the Hot feed: Hot karma (24–42) >> New karma (1–3).
  #
  # Order within NewEvents: each post has a distinct createdAt timestamp in the last 10 minutes.
  # Descending by createdAt equals descending by postId: post-30, post-29, …, post-21.
  # karma per post (with <=10 voters/post): postId 30→1, 29→2, 28→3, 27→2, 26→1,
  #                                         25→2, 24→1, 23→2, 22→1, 21→2
  Scenario: New posts
    Given data folder 'data/csv' was ingested
    Then new posts endpoint returns 10 ranked results
      | postId  | karma |
      | post-30 | 1     |
      | post-29 | 2     |
      | post-28 | 3     |
      | post-27 | 2     |
      | post-26 | 1     |
      | post-25 | 2     |
      | post-24 | 1     |
      | post-23 | 2     |
      | post-22 | 1     |
      | post-21 | 2     |

  # Top ranking: top_score = upvotes − downvotes, all-time, no time window.
  # Posts 41-50: 61–70% upvote rate, 500 voters each → karma 110-200/post, highest across all generators.
  # karma = 500 × (2 × upvote% − 1): 61%→110, 62%→120, …, 70%→200
  # Events are 366-730 days old — outside YEAR window, only visible in ALL.
  # karma per post: postId 41→110, 42→120, ..., 50→200  (upvote% = 61 + (postId−41))
  Scenario: Top posts for ALL
    Given data folder 'data/csv' was ingested
    Then top posts endpoint returns 10 ranked results
      | postId  | karma |
      | post-50 | 200   |
      | post-49 | 190   |
      | post-48 | 180   |
      | post-47 | 170   |
      | post-46 | 160   |
      | post-45 | 150   |
      | post-44 | 140   |
      | post-43 | 130   |
      | post-42 | 120   |
      | post-41 | 110   |

  # Top/YEAR: 365-day window.
  # BestEvents events are 31-364 days old → all inside the YEAR window.
  # TopEvents events are 366-730 days old → outside YEAR, so they don't compete here.
  # karma per post: postId 01→66, 02→68, ..., 10→84  (upvote% = 83 + (postId−1))
  Scenario: Top posts for YEAR
    Given data folder 'data/csv' was ingested
    Then top posts for YEAR returns 10 ranked results
      | postId  | karma |
      | post-10 | 84    |
      | post-09 | 82    |
      | post-08 | 80    |
      | post-07 | 78    |
      | post-06 | 76    |
      | post-05 | 74    |
      | post-04 | 72    |
      | post-03 | 70    |
      | post-02 | 68    |
      | post-01 | 66    |

  # Top/MONTH: 30-day window.
  # RisingEvents events are 8-29 days old → all inside the MONTH window.
  # NewEvents createdAt 1–10 s ago → also in MONTH, but karma max=20 < 44.
  # HotEvents createdAt 9–54 min ago → also in MONTH, but karma max=42 < 44.
  # karma per post: postId 31→44, 32→46, ..., 40→62  (upvote% = 72 + (postId−31))
  Scenario: Top posts for MONTH
    Given data folder 'data/csv' was ingested
    Then top posts for MONTH returns 10 ranked results
      | postId  | karma |
      | post-40 | 62    |
      | post-39 | 60    |
      | post-38 | 58    |
      | post-37 | 56    |
      | post-36 | 54    |
      | post-35 | 52    |
      | post-34 | 50    |
      | post-33 | 48    |
      | post-32 | 46    |
      | post-31 | 44    |

  # Top/WEEK: 7-day window.
  # HotEvents createdAt 9–54 min ago → inside WEEK, karma 24-42 (highest in window).
  # NewEvents createdAt 1–10 s ago → also in WEEK, but karma max=20 < 24.
  # RisingEvents createdAt 8-29 days old → outside WEEK, so they don't compete here.
  # karma per post: postId 11→24, 12→26, ..., 20→42  (upvote% = 62 + (postId−11))
  Scenario: Top posts for WEEK
    Given data folder 'data/csv' was ingested
    Then top posts for WEEK returns 10 ranked results
      | postId  | karma |
      | post-20 | 42    |
      | post-19 | 40    |
      | post-18 | 38    |
      | post-17 | 36    |
      | post-16 | 34    |
      | post-15 | 32    |
      | post-14 | 30    |
      | post-13 | 28    |
      | post-12 | 26    |
      | post-11 | 24    |

  # Top/DAY: 24-hour window.
  # HotEvents createdAt 9–54 min ago → fully inside the DAY window, karma 24-42.
  # NewEvents createdAt 1–10 s ago → also in DAY window, but karma max=20 < 24.
  # karma per post: postId 11→24, 12→26, ..., 20→42  (upvote% = 62 + (postId−11))
  Scenario: Top posts for DAY
    Given data folder 'data/csv' was ingested
    Then top posts for DAY returns 10 ranked results
      | postId  | karma |
      | post-20 | 42    |
      | post-19 | 40    |
      | post-18 | 38    |
      | post-17 | 36    |
      | post-16 | 34    |
      | post-15 | 32    |
      | post-14 | 30    |
      | post-13 | 28    |
      | post-12 | 26    |
      | post-11 | 24    |
