Feature: test UserActivityController

  # ═══════════════════════════════════════════════════════════════════════════════
  # FIXTURE DATA  (src/test/resources/data/csv/)
  # Generated by EventGenerator implementations in cucumber/helper/generator/.
  # Run EventGeneratorTest to regenerate fresh CSV files before Cucumber tests.
  # ═══════════════════════════════════════════════════════════════════════════════
  # Five CSV files, 300 users × 50 posts = 15,000 events total.
  # Each file is designed for a specific algorithm so different ranking algorithms
  # produce visibly different top-10 results on the same shared dataset.
  # Files share no post IDs and can be ingested in parallel.
  #
  # Columns: userId, postId, action (UPVOTE|DOWNVOTE), date (ISO-8601 UTC)
  #
  # ┌──────────────────────┬───────────┬──────┬────────────────────────────────────────────────────┐
  # │ File                 │ Posts     │ Up % │ Date pattern / intent                              │
  # ├──────────────────────┼───────────┼──────┼────────────────────────────────────────────────────┤
  # │ events-best.csv      │ post-01…10│  80% │ Spread 0–180 days — steady quality baseline        │
  # ├──────────────────────┼───────────┼──────┼────────────────────────────────────────────────────┤
  # │ events-hot.csv       │ post-11…20│  90% │ ALL events within the last 60 minutes              │
  # │                      │           │      │ → first_seen ≈ 60 min → wins Hot (time dominates)  │
  # ├──────────────────────┼───────────┼──────┼────────────────────────────────────────────────────┤
  # │ events-new.csv       │ post-21…30│  85% │ All events within the last 24 hours                │
  # │                      │           │      │ → first_seen ≈ 24 h → 2nd in Hot                   │
  # ├──────────────────────┼───────────┼──────┼────────────────────────────────────────────────────┤
  # │ events-rising.csv    │ post-31…40│ mix  │ Old baseline (120–180 days) + recent spike (0–7 d) │
  # ├──────────────────────┼───────────┼──────┼────────────────────────────────────────────────────┤
  # │ events-top.csv       │ post-41…50│  95% │ Spread 0–365 days — net = 270/post                 │
  # │                      │           │      │ → highest net score → wins Top; old first_seen     │
  # │                      │           │      │   means it does NOT win Hot                        │
  # └──────────────────────┴───────────┴──────┴────────────────────────────────────────────────────┘
  #
  # ── EXPECTED RANKING DIFFERENCES ──────────────────────────────────────────────────────────────────
  #
  # Hot  (Reddit formula: hot_score = log₁₀(net) + (firstSeenSec − 1134028003) / 45 000)
  #   Time dominates — every 12.5 h of age costs ~1 hot_score point.
  #   posts 11-20: first_seen ≈  60 min,  net=240  →  hot_score ≈ 14 189  ← rank 1
  #   posts 21-30: first_seen ≈  24 h,   net=210  →  hot_score ≈ 14 187  ← rank 2
  #   posts 31-40: first_seen ≈ 120+ d,  net≈175  →  hot_score ≈ 13 856  ← rank 3
  #   posts  1-10: first_seen ≈ 180 d,   net=180  →  hot_score ≈ 13 844  ← rank 4
  #   posts 41-50: first_seen ≈ 365 d,   net=270  →  hot_score ≈ 13 489  ← rank 5
  #
  # Top  (top_score = upvotes − downvotes, filtered by window)
  #
  #   Window │ Winner       │ Why
  #   ───────┼──────────────┼──────────────────────────────────────────────────────
  #   ALL    │ posts 41-50  │ 95% upvote across full history  → net = 270/post
  #   YEAR   │ posts 41-50  │ events spread 0-364 d, all inside 365-d window → 270
  #   MONTH  │ posts 11-20  │ TopEvents has ~22 net in 30 d; HotEvents has 240
  #   WEEK   │ posts 11-20  │ TopEvents has  ~5 net in  7 d; HotEvents has 240
  #   DAY    │ posts 11-20  │ TopEvents has  ~0 net in  1 d; HotEvents has 240
  #
  #   Key insight: sustained quality (TopEvents) wins long windows;
  #                recent burst (HotEvents) wins short windows.
  # ════════════════════════════════════════════════════════════════════════════

  Scenario: prepare data
    Given index 'user-activity' exists
    Given data folder 'data/csv' ingested

  # Hot ranking: Reddit's hot_score = log₁₀(net) + (firstSeenSec − anchor) / 45 000.
  # Time dominates: posts 11-20 have first_seen ≈ 60 min vs. 24 h for posts 21-30.
  # Separation ≈ 1.84 hot_score points → posts 11-20 win Hot.
  Scenario: Hot posts
    Given data folder 'data/csv' was ingested
    Then hot posts endpoint returns 10 ranked results
      | post-11 |
      | post-12 |
      | post-13 |
      | post-14 |
      | post-15 |
      | post-16 |
      | post-17 |
      | post-18 |
      | post-19 |
      | post-20 |

  # Top ranking: top_score = upvotes − downvotes, all-time, no time window.
  # Posts 41-50 use 95% upvote rate → net = 270/post, beating all other generators.
  # HotEvents (90% → 240) and NewEvents (85% → 210) rank below TopEvents.
  Scenario: Top posts for ALL
    Given data folder 'data/csv' was ingested
    Then top posts endpoint returns 10 ranked results
      | post-41 |
      | post-42 |
      | post-43 |
      | post-44 |
      | post-45 |
      | post-46 |
      | post-47 |
      | post-48 |
      | post-49 |
      | post-50 |

  # Top/YEAR: 365-day window. TopEvents events span 0-364 days — all inside the window.
  # Net score identical to ALL-time (270/post). Posts 41-50 still beat HotEvents (240).
  Scenario: Top posts for YEAR
    Given data folder 'data/csv' was ingested
    Then top posts for YEAR returns 10 ranked results
      | post-41 |
      | post-42 |
      | post-43 |
      | post-44 |
      | post-45 |
      | post-46 |
      | post-47 |
      | post-48 |
      | post-49 |
      | post-50 |

  # Top/MONTH: 30-day window. TopEvents has ~22 net in-window (≈7% of events).
  # HotEvents has all 240 net in-window (events are within 60 min). Posts 11-20 win.
  Scenario: Top posts for MONTH
    Given data folder 'data/csv' was ingested
    Then top posts for MONTH returns 10 ranked results
      | post-11 |
      | post-12 |
      | post-13 |
      | post-14 |
      | post-15 |
      | post-16 |
      | post-17 |
      | post-18 |
      | post-19 |
      | post-20 |

  # Top/WEEK: 7-day window. TopEvents has ~5 net in-window (≈2% of events).
  # HotEvents still has full 240 net (events within 60 min). Posts 11-20 win.
  Scenario: Top posts for WEEK
    Given data folder 'data/csv' was ingested
    Then top posts for WEEK returns 10 ranked results
      | post-11 |
      | post-12 |
      | post-13 |
      | post-14 |
      | post-15 |
      | post-16 |
      | post-17 |
      | post-18 |
      | post-19 |
      | post-20 |

  # Top/DAY: 24-hour window. TopEvents has ~0 net in-window (<1 event/post expected).
  # HotEvents has all 240 net (events within 60 min). NewEvents has 210 net (within 24 h).
  # Posts 11-20 win by largest margin — demonstrates why short-window Top ≠ all-time Top.
  Scenario: Top posts for DAY
    Given data folder 'data/csv' was ingested
    Then top posts for DAY returns 10 ranked results
      | post-11 |
      | post-12 |
      | post-13 |
      | post-14 |
      | post-15 |
      | post-16 |
      | post-17 |
      | post-18 |
      | post-19 |
      | post-20 |
