Feature: test UserActivityController

  # ═══════════════════════════════════════════════════════════════════════════════
  # FIXTURE DATA  (src/test/resources/data/csv/)
  # Generated by EventGenerator implementations in cucumber/helper/generator/.
  # Run EventGeneratorTest to regenerate fresh CSV files before Cucumber tests.
  # ═══════════════════════════════════════════════════════════════════════════════
  # Five CSV files, 100 users × 50 posts = 5,000 events total.
  # Each file is designed for a specific algorithm so different ranking algorithms
  # produce visibly different top-10 results on the same shared dataset.
  # Files share no post IDs and can be ingested in parallel.
  #
  # Columns: userId, postId, action (UPVOTE|DOWNVOTE), date (ISO-8601 UTC)
  #
  # ┌──────────────────────┬───────────┬──────┬────────────────────────────────────────────────────┐
  # │ File                 │ Posts     │ Up % │ Date pattern / intent                              │
  # ├──────────────────────┼───────────┼──────┼────────────────────────────────────────────────────┤
  # │ events-best.csv      │ post-01…10│  80% │ Spread 0–180 days — steady quality baseline        │
  # ├──────────────────────┼───────────┼──────┼────────────────────────────────────────────────────┤
  # │ events-hot.csv       │ post-11…20│  90% │ ALL events within the last 60 minutes              │
  # │                      │           │      │ → first_seen ≈ 60 min → wins Hot (time dominates)  │
  # ├──────────────────────┼───────────┼──────┼────────────────────────────────────────────────────┤
  # │ events-new.csv       │ post-21…30│  85% │ All events within the last 24 hours                │
  # │                      │           │      │ → first_seen ≈ 24 h → 2nd in Hot                   │
  # ├──────────────────────┼───────────┼──────┼────────────────────────────────────────────────────┤
  # │ events-rising.csv    │ post-31…40│ mix  │ Old baseline (120–180 days) + recent spike (0–7 d) │
  # ├──────────────────────┼───────────┼──────┼────────────────────────────────────────────────────┤
  # │ events-top.csv       │ post-41…50│  95% │ Spread 0–365 days — net = 90/post                 │
  # │                      │           │      │ → highest net score → wins Top; old first_seen     │
  # │                      │           │      │   means it does NOT win Hot                        │
  # └──────────────────────┴───────────┴──────┴────────────────────────────────────────────────────┘
  #
  # ── EXPECTED RANKING DIFFERENCES ──────────────────────────────────────────────────────────────────
  #
  # Hot  (Reddit formula: hot_score = log₁₀(net) + (firstSeenSec − 1134028003) / 45 000)
  #   Time dominates — every 12.5 h of age costs ~1 hot_score point.
  #   posts 11-20: first_seen ≈  60 min,  net=80  →  hot_score ≈ 13 516  ← rank 1
  #   posts 21-30: first_seen ≈  24 h,   net=70  →  hot_score ≈ 13 514  ← rank 2
  #   posts 31-40: first_seen ≈ 120+ d,  net≈58  →  hot_score ≈ 13 141  ← rank 3
  #   posts  1-10: first_seen ≈ 180 d,   net=60  →  hot_score ≈ 13 489  ← rank 4
  #   posts 41-50: first_seen ≈ 365 d,   net=90  →  hot_score ≈ 13 131  ← rank 5
  #
  # Top  (top_score = upvotes − downvotes, filtered by window)
  #
  #   Window │ Winner       │ karma │ Why
  #   ───────┼──────────────┼───────┼──────────────────────────────────────────────────────
  #   ALL    │ posts 41-50  │   90  │ 95% upvote across full history  → 95 up − 5 down
  #   YEAR   │ posts 41-50  │   90  │ events spread 0-364 d, all inside 365-d window → 90
  #   MONTH  │ posts 11-20  │   80  │ HotEvents: all 100 events within 60 min → 90 up − 10 down
  #   WEEK   │ posts 11-20  │   80  │ HotEvents: all 100 events within 60 min → 90 up − 10 down
  #   DAY    │ posts 11-20  │   80  │ HotEvents: all 100 events within 60 min → 90 up − 10 down
  #
  #   karma is exact because isUpvote() uses a deterministic hash:
  #     bucket = floorMod(userId*31 + postId*17, 100); gcd(31,100)=1
  #     → for userId 1-100 the buckets are a full permutation of 0-99
  #     → upvotePercent% of 100 users always upvote, regardless of postId
  #
  #   Key insight: sustained quality (TopEvents) wins long windows;
  #                recent burst (HotEvents) wins short windows.
  # ════════════════════════════════════════════════════════════════════════════

  Scenario: prepare data
    Given index 'user-activity' exists
    Given data folder 'data/csv' created in tmp directory
    Given data folder 'data/csv' ingested

  # Hot ranking: Reddit's hot_score = log₁₀(net) + (firstSeenSec − anchor) / 45 000.
  # Time dominates: posts 11-20 have first_seen ≈ 60 min vs. 24 h for posts 21-30.
  # Separation ≈ 1.84 hot_score points → posts 11-20 win Hot.
  # karma = 80: 90% upvote × 100 users → 90 up − 10 down = 80.
  Scenario: Hot posts
    Given data folder 'data/csv' was ingested
    Then hot posts endpoint returns 10 ranked results
      | postId  | karma |
      | post-11 | 80    |
      | post-12 | 80    |
      | post-13 | 80    |
      | post-14 | 80    |
      | post-15 | 80    |
      | post-16 | 80    |
      | post-17 | 80    |
      | post-18 | 80    |
      | post-19 | 80    |
      | post-20 | 80    |

  # Top ranking: top_score = upvotes − downvotes, all-time, no time window.
  # Posts 41-50 use 95% upvote rate → net = 90/post, beating all other generators.
  # HotEvents (90% → 80) and NewEvents (85% → 70) rank below TopEvents.
  # karma = 90: 95% upvote × 100 users → 95 up − 5 down = 90.
  Scenario: Top posts for ALL
    Given data folder 'data/csv' was ingested
    Then top posts endpoint returns 10 ranked results
      | postId  | karma |
      | post-41 | 90    |
      | post-42 | 90    |
      | post-43 | 90    |
      | post-44 | 90    |
      | post-45 | 90    |
      | post-46 | 90    |
      | post-47 | 90    |
      | post-48 | 90    |
      | post-49 | 90    |
      | post-50 | 90    |

  # Top/YEAR: 365-day window. TopEvents events span 0-364 days — all inside the window.
  # Net score identical to ALL-time (90/post). Posts 41-50 still beat HotEvents (80).
  # karma = 90: same 95 up − 5 down, all events within the 365-d window.
  Scenario: Top posts for YEAR
    Given data folder 'data/csv' was ingested
    Then top posts for YEAR returns 10 ranked results
      | postId  | karma |
      | post-41 | 90    |
      | post-42 | 90    |
      | post-43 | 90    |
      | post-44 | 90    |
      | post-45 | 90    |
      | post-46 | 90    |
      | post-47 | 90    |
      | post-48 | 90    |
      | post-49 | 90    |
      | post-50 | 90    |

  # Top/MONTH: 30-day window. HotEvents has all 80 net in-window (events within 60 min).
  # TopEvents has only ~7 net in-window (≈7% of events fall inside 30 d). Posts 11-20 win.
  # karma = 80: all 100 HotEvents votes within 60 min, well inside the 30-d window.
  Scenario: Top posts for MONTH
    Given data folder 'data/csv' was ingested
    Then top posts for MONTH returns 10 ranked results
      | postId  | karma |
      | post-11 | 80    |
      | post-12 | 80    |
      | post-13 | 80    |
      | post-14 | 80    |
      | post-15 | 80    |
      | post-16 | 80    |
      | post-17 | 80    |
      | post-18 | 80    |
      | post-19 | 80    |
      | post-20 | 80    |

  # Top/WEEK: 7-day window. HotEvents still has full 80 net (events within 60 min).
  # TopEvents has ~5 net in-window (≈2% of events fall inside 7 d). Posts 11-20 win.
  # karma = 80: all 100 HotEvents votes within 60 min, well inside the 7-d window.
  Scenario: Top posts for WEEK
    Given data folder 'data/csv' was ingested
    Then top posts for WEEK returns 10 ranked results
      | postId  | karma |
      | post-11 | 80    |
      | post-12 | 80    |
      | post-13 | 80    |
      | post-14 | 80    |
      | post-15 | 80    |
      | post-16 | 80    |
      | post-17 | 80    |
      | post-18 | 80    |
      | post-19 | 80    |
      | post-20 | 80    |

  # Top/DAY: 24-hour window. HotEvents has all 80 net (events within 60 min).
  # TopEvents has ~0 net in-window (<1 event/post expected). Posts 11-20 win.
  # karma = 80: all 100 HotEvents votes within 60 min, well inside the 24-h window.
  Scenario: Top posts for DAY
    Given data folder 'data/csv' was ingested
    Then top posts for DAY returns 10 ranked results
      | postId  | karma |
      | post-11 | 80    |
      | post-12 | 80    |
      | post-13 | 80    |
      | post-14 | 80    |
      | post-15 | 80    |
      | post-16 | 80    |
      | post-17 | 80    |
      | post-18 | 80    |
      | post-19 | 80    |
      | post-20 | 80    |
