package my.javacraft.elastic.service;

import co.elastic.clients.elasticsearch.ElasticsearchClient;
import co.elastic.clients.elasticsearch._types.ElasticsearchException;
import co.elastic.clients.elasticsearch._types.Script;
import co.elastic.clients.elasticsearch.core.IndexRequest;
import co.elastic.clients.elasticsearch.core.UpdateRequest;
import co.elastic.clients.json.JsonData;
import co.elastic.clients.json.JsonpUtils;
import java.io.IOException;
import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.Map;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import my.javacraft.elastic.config.Constants;
import my.javacraft.elastic.model.Post;
import my.javacraft.elastic.service.post.IdGenerator;
import org.springframework.stereotype.Service;

/**
 * Manages post documents in the 'posts' index.
 * One document per post; document ID is a 6-character alphanumeric string
 * generated by {@link IdGenerator}.
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class PostService {

    private final ElasticsearchClient esClient;
    private final IdGenerator idGenerator;

    /**
     * Indexes a new post document with a server-generated ID and timestamp.
     * This is a strict insert — calling it twice with the same author produces two
     * independent posts, exactly as Reddit handles duplicate submissions.
     * Karma starts at zero; subsequent votes adjust it via {@link #updateKarma}.
     *
     * @param authorUserId userId of the person submitting the post
     * @return the fully-populated {@link Post} including the generated {@code postId} and {@code createdAt}
     */
    public Post submitPost(String authorUserId) throws IOException {
        String postId    = idGenerator.generateUniquePostId();
        String createdAt = Instant.now().truncatedTo(ChronoUnit.SECONDS).toString();
        Post post = new Post(postId, authorUserId, createdAt, 0L);

        IndexRequest<Post> request = new IndexRequest.Builder<Post>()
                .index(Constants.INDEX_POSTS)
                .id(postId)
                .document(post)
                .build();

        log.debug("submitPost request: {}", JsonpUtils.toJsonString(request, esClient._jsonpMapper()));

        esClient.index(request);
        log.info("post submitted (postId='{}', author='{}')", postId, authorUserId);
        return post;
    }

    /**
     * Atomically adjusts the karma of an existing post document by {@code delta}.
     * Uses a Painless script so the increment is race-free under concurrent votes.
     *
     * <p>If the post document does not exist (orphaned vote, or posts index not yet seeded),
     * the update is silently skipped with a WARN log rather than propagating an exception.
     * Karma is best-effort: missing-post votes simply do not influence the score.
     *
     * @param postId post to update
     * @param delta  +1 / −1 for new vote; +2 / −2 for vote flip; never 0 (callers skip)
     */
    public void updateKarma(String postId, int delta) throws IOException {
        Script script = Script.of(s -> s
                .source("ctx._source." + Constants.KARMA + " += params.delta")
                .params(Map.of("delta", JsonData.of(delta)))
        );

        var request = new UpdateRequest.Builder<Post, Post>()
                .index(Constants.INDEX_POSTS)
                .id(postId)
                .script(script)
                .build();

        log.debug("updateKarma request: {}", JsonpUtils.toJsonString(request, esClient._jsonpMapper()));

        try {
            var result = esClient.update(request, Post.class);
            log.debug("karma updated (postId='{}', delta={}, result='{}')", postId, delta, result.result());
        } catch (ElasticsearchException ex) {
            if ("document_missing_exception".equals(ex.error().type())) {
                log.warn("karma update skipped — post '{}' not found in '{}' index (orphaned vote)",
                        postId, Constants.INDEX_POSTS);
                return;
            }
            throw ex;
        }
    }
}
