package my.javacraft.elastic.service;

import co.elastic.clients.elasticsearch.ElasticsearchClient;
import co.elastic.clients.elasticsearch._types.ElasticsearchException;
import co.elastic.clients.elasticsearch._types.Script;
import co.elastic.clients.elasticsearch.core.IndexRequest;
import co.elastic.clients.elasticsearch.core.UpdateRequest;
import co.elastic.clients.json.JsonData;
import co.elastic.clients.json.JsonpUtils;
import java.io.IOException;
import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.Map;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import my.javacraft.elastic.config.Constants;
import my.javacraft.elastic.model.Post;
import my.javacraft.elastic.service.post.IdGenerator;
import org.springframework.stereotype.Service;

/**
 * Manages post documents in the 'posts' index.
 * Document ID is a 6-character alphanumeric string generated by {@link IdGenerator}.
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class PostService {

    /** Unix-second epoch anchor used in Reddit's hot formula (Dec 8, 2005). */
    static final long HOT_EPOCH_ANCHOR = 1_134_028_003L;

    /** Score divisor: every 45 000 s ≈ 12.5 h of age adds +1 to hot_score. */
    static final double HOT_TIME_SCALE = 45_000.0;

    /**
     * Painless script executed on every vote.
     * Atomically updates {@code karma} and recomputes {@code hotScore}:
     * <pre>
     *   karma    += delta
     *   order     = log₁₀(max(|karma|, 1)) × sign(karma)
     *   hotScore  = order + (createdAt_epoch − HOT_EPOCH_ANCHOR) / HOT_TIME_SCALE
     * </pre>
     */
    private static final String SCORES_SCRIPT =
            "ctx._source.karma += params.delta; " +
            "long k = ctx._source.karma; " +
            "double sign = k > 0 ? 1.0 : (k < 0 ? -1.0 : 0.0); " +
            "double order = Math.log10(Math.max((double) Math.abs(k), 1.0)) * sign; " +
            "long epochSec = Instant.parse(ctx._source.createdAt).getEpochSecond(); " +
            "ctx._source.hotScore = order + (epochSec - 1134028003L) / 45000.0;";

    private final ElasticsearchClient esClient;
    private final IdGenerator idGenerator;

    /**
     * Indexes a new post document with a server-generated ID and timestamp.
     * Strict insert — calling it twice with the same author produces two independent posts,
     * exactly as Reddit handles duplicate submissions.
     * Karma starts at zero; hotScore starts at the pure time-only component.
     * Both are updated on every subsequent vote via {@link #updateScores}.
     *
     * @param authorUserId userId of the person submitting the post
     * @return the fully-populated {@link Post} including the generated {@code postId} and {@code createdAt}
     */
    public Post submitPost(String authorUserId) throws IOException {
        String postId    = idGenerator.generateUniquePostId();
        Instant created  = Instant.now().truncatedTo(ChronoUnit.SECONDS);
        String createdAt = created.toString();
        double hotScore  = (created.getEpochSecond() - HOT_EPOCH_ANCHOR) / HOT_TIME_SCALE;
        Post post = new Post(postId, authorUserId, createdAt, 0L, hotScore);

        IndexRequest<Post> request = new IndexRequest.Builder<Post>()
                .index(Constants.INDEX_POSTS)
                .id(postId)
                .document(post)
                .build();

        log.debug("submitPost request: {}", JsonpUtils.toJsonString(request, esClient._jsonpMapper()));

        esClient.index(request);
        log.info("post submitted (postId='{}', author='{}')", postId, authorUserId);
        return post;
    }

    /**
     * Atomically updates {@code karma} and {@code hotScore} of an existing post document.
     * Uses a single Painless script so both values change in one round-trip and are race-free
     * under concurrent votes.
     *
     * <p>If the post document does not exist (orphaned vote), the update is silently skipped
     * with a WARN log. Scores are best-effort for orphaned votes.
     *
     * @param postId post to update
     * @param delta  +1/−1 for new vote; +2/−2 for vote flip; never 0 (callers skip)
     */
    public void updateScores(String postId, int delta) throws IOException {
        Script script = Script.of(s -> s
                .source(SCORES_SCRIPT)
                .params(Map.of("delta", JsonData.of(delta)))
        );

        var request = new UpdateRequest.Builder<Post, Post>()
                .index(Constants.INDEX_POSTS)
                .id(postId)
                .script(script)
                .build();

        log.debug("updateScores request: {}", JsonpUtils.toJsonString(request, esClient._jsonpMapper()));

        try {
            var result = esClient.update(request, Post.class);
            log.debug("scores updated (postId='{}', delta={}, result='{}')", postId, delta, result.result());
        } catch (ElasticsearchException ex) {
            if ("document_missing_exception".equals(ex.error().type())) {
                log.warn("scores update skipped — post '{}' not found in '{}' index (orphaned vote)",
                        postId, Constants.INDEX_POSTS);
                return;
            }
            throw ex;
        }
    }
}
