package dev.nklip.javacraft.xlspaceship.engine.game;

import dev.nklip.javacraft.xlspaceship.engine.game.ships.Spaceship;
import dev.nklip.javacraft.xlspaceship.engine.game.ships.Winger;
import dev.nklip.javacraft.xlspaceship.engine.service.RandomProvider;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

public class BoardTest {

    @Test
    public void testToStringCase01() {
        Board board = new Board();
        Assertions.assertEquals(
                """
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                """,
                board.toString()
        );
    }

    @Test
    public void testSetSpaceshipCase01() {

        Board board = new Board();
        Winger winger = new Winger(1);

        board.printSpaceship(0, 0, winger);

        Assertions.assertEquals(
                """
                *.*.............
                *.*.............
                .*..............
                *.*.............
                *.*.............
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                """,
                board.toString()
        );
    }

    @Test
    public void testSetSpaceshipCase02() {

        Board board = new Board();
        Winger winger = new Winger( 2);

        board.printSpaceship(0, 0, winger);

        Assertions.assertEquals(
                """
                **.**...........
                ..*.............
                **.**...........
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                """,
                board.toString()
        );
    }

    @Test
    public void testSetSpaceshipCase03() {
        Board board = new Board();
        Winger winger = new Winger( 1);

        int x = 16 - winger.getWidth();
        int y = 16 - winger.getHeight();

        Assertions.assertTrue(board.isSettable(x, y, winger));
        board.printSpaceship(x, y, winger);

        Assertions.assertEquals(
                """
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                .............*.*
                .............*.*
                ..............*.
                .............*.*
                .............*.*
                """,
                board.toString()
        );
    }

    @Test
    public void testSetSpaceshipCase04() {
        Board board = new Board();
        RandomProvider randomProvider = Mockito.mock(RandomProvider.class);
        SingleCellShip spaceship = new SingleCellShip();

        for (int x = 0; x < Board.SIZE; x++) {
            for (int y = 0; y < Board.SIZE; y++) {
                if (x < Board.SIZE - 2 || y < Board.SIZE - 2) {
                    board.update(x, y, Board.MISS);
                }
            }
        }

        Mockito.when(randomProvider.generateCell(Mockito.anyInt())).thenReturn(0);

        Assertions.assertTrue(board.setSpaceship(randomProvider, spaceship));
        Assertions.assertEquals("*", board.getValue(Board.SIZE - 1, Board.SIZE - 1));
        Assertions.assertEquals(1, spaceship.getHealth());
        Mockito.verify(randomProvider, Mockito.atLeastOnce()).generateCell(Board.SIZE);
    }

    @Test
    public void testIsSettableCase01() {
        Board board = new Board();
        Winger winger1 = new Winger( 1);
        Winger winger2 = new Winger( 2);

        Assertions.assertTrue(board.isSettable(0, 0, winger1));
        board.printSpaceship(0, 0, winger1);

        Assertions.assertFalse(board.isSettable(0, 0, winger2));
        Assertions.assertTrue(board.isSettable(5, 5, winger2));
        board.printSpaceship(5, 5, winger2);

        Assertions.assertEquals(
                """
                *.*.............
                *.*.............
                .*..............
                *.*.............
                *.*.............
                .....**.**......
                .......*........
                .....**.**......
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                """,
                board.toString()
        );
    }

    @Test
    public void testIsSettableCase02() {
        Board board = new Board();
        Winger winger1 = new Winger( 1);
        Winger winger2 = new Winger( 2);

        Assertions.assertTrue(board.isSettable(16 - winger1.getWidth(), 16 - winger1.getHeight(), winger1));
        board.printSpaceship(0, 0, winger1);

        Assertions.assertFalse(board.isSettable(0, 0, winger2));
        Assertions.assertTrue(board.isSettable(5, 5, winger2));
        board.printSpaceship(5, 5, winger2);

        Assertions.assertEquals(
                """
                *.*.............
                *.*.............
                .*..............
                *.*.............
                *.*.............
                .....**.**......
                .......*........
                .....**.**......
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                """,
                board.toString()
        );
    }

    @Test
    public void testIsSettableCase03() {
        Board board = new Board();
        Winger topWinger = new Winger(1);
        Winger bottomWinger = new Winger(1);

        board.printSpaceship(0, 6, bottomWinger);

        Assertions.assertTrue(board.isSettable(0, 0, topWinger));

        Assertions.assertEquals(
                """
                ................
                ................
                ................
                ................
                ................
                ................
                *.*.............
                *.*.............
                .*..............
                *.*.............
                *.*.............
                ................
                ................
                ................
                ................
                ................
                """,
                board.toString()
        );
    }

    @Test
    public void testIsSettableCase04() {
        Board board = new Board();
        Winger winger = new Winger(1);

        Assertions.assertFalse(board.isSettable(14, 0, winger));

        Assertions.assertEquals(
                """
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                """,
                board.toString()
        );
    }

    @Test
    public void testClearResetsSpaceshipLives() {
        Board board = new Board();
        Winger winger = new Winger(1);

        board.printSpaceship(0, 0, winger);
        Assertions.assertEquals(9, winger.getHealth());

        board.clear();
        Assertions.assertEquals(0, winger.getHealth());
        Assertions.assertEquals(
                """
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                """,
                board.toString()
        );

        board.printSpaceship(5, 5, winger);
        Assertions.assertEquals(9, winger.getHealth());
    }

    @Test
    public void testHex() {
        int x = 0;
        for (int i = 0; i < 15; i++) {
            x++;
        }
        //Assertions.assertEquals(16, x);
        String value = Integer.toString(x, 16);
        Assertions.assertEquals("f", value);
    }

    private static final class SingleCellShip extends Spaceship {

        private SingleCellShip() {
            super(1, 1, 1);
        }

        @Override
        protected Cell[][] formA() {
            ship[0] = string2cells("*");
            return ship;
        }

        @Override
        protected Cell[][] formB() {
            return formA();
        }

        @Override
        protected Cell[][] formC() {
            return formA();
        }

        @Override
        protected Cell[][] formD() {
            return formA();
        }
    }

}
