quarkus.config.locations=${shardshop.routing.config:file:/etc/shardshop/routing/application.properties}
%test.quarkus.config.locations=routing-test.properties
%test.shardshop.id.generator-id=1
quarkus.datasource.devservices.enabled=false
quarkus.datasource.db-kind=postgresql
quarkus.datasource.active=false
quarkus.http.limits.max-body-size=32K
quarkus.http.read-timeout=4s
%test.quarkus.http.port=0
%test.quarkus.http.test-port=0
