server:
  port: 8081
spring:
  application:
    name: meme-keeper
  datasource:
    url: jdbc:h2:mem:soap2rest;MODE=Oracle;
    username: sa
    password: sa # don't keep password like that for PROD stage
    driverClassName: org.h2.Driver
  liquibase:
    enabled: true
    change-log: classpath:/liquibase/v1/changelog.xml
  artemis:
    mode: embedded
    embedded:
      persistent: false
      queues: smart-metrics-queue
  jackson:
    serialization:
      INDENT_OUTPUT: true # provides pretty output
  jpa:
    hibernate:
      ddl-auto: none
      database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: false
        format_sql: true
  h2:
    console:
      enabled: true
      path: /console

soap2rest:
  rest:
    smart:
      message: REST SmartResource is up!

# sort endpoints in Swagger
springdoc:
  swagger-ui:
    # Tag groups (controllers) sorted A -> Z
    tagsSorter: alpha
    # Operations sorted A -> Z by path within each tag
    operationsSorter: alpha