server:
  port: 8050

spring:
  config:
    import: classpath:openflights-jpa-defaults.yaml

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    # Tag groups (controllers) sorted A -> Z
    tagsSorter: alpha
    # Operations sorted A -> Z by path within each tag
    operationsSorter: alpha
