server.port: 8079
management.port: 9001
management.address: 127.0.0.1

# thymeleaf
spring.thymeleaf.mode=HTML

# sort endpoints in Swagger
# Tag groups (controllers) sorted A -> Z
springdoc.swagger-ui.tagsSorter = alpha
# Operations sorted A -> Z by path within each tag
springdoc.swagger-ui.operationsSorter = alpha